//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ddjdemo.rc
//
#define IDS_DDJDEMO                     1
#define IDB_DDJDEMO                     1
#define IDS_DDJDEMO_PPG                 2
#define IDB_DDJDEMO1                    2
#define IDI_ABOUTDLL                    10
#define IDI_ABOUTDLL1                   11
#define IDD_ABOUTBOX_DDJDEMO            100
#define IDS_DDJDEMO_PPG_CAPTION         101
#define IDD_PROPPAGE_DDJDEMO            101
#define IDD_ABOUTBOX_DDJDEMO1           102
#define IDD_PROPPAGE_DDJDEMO1           103
#define IDS_PROPERTIESVERB              200
#define IDC_EDIT1                       201
#define IDC_EDIT2                       202

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
